### ISSUE TITLE
Force new authorization value through cache.

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/http2-cache.js#112]
If a request with auth 1 is made, and the response is `cache-control: public` or some other shareable cache directive, then any subsequent requests with auth 2 will return directly from the client side cache.

This can cause push promises to be cancelled if auth1 expires.  To fix this, there should be a mechanism that forces the auth2 request through to the server.

To do this, the http2-cache.js could store the original authorization field for the request in the cache entries for all subsequently delivered push promises (note, these push promises may or may not already have that authorization header attached).  If it is not present in the push promise request, then it should add the value.  Part 2) when a application initiated request does not match the authorization field, then the client side cache should send the request regardless of cache-control: public or other shareable cache directive

**Comment by hthetiot** [comment]
I think that some what what was done before:
- https://github.com/kaazing/http2-cache.js/commit/20970fcafac0471a1d837c4950e2b96055bc7800#diff-63fdc6a01d0ec0cbf9772723f2356e46

**Comment by hthetiot** [comment]
> also asked for an etag to be put on the new auth request with the data from the old auth request, such that a 304 can result in not needing to update the cache
