### ISSUE TITLE
Non http2 request does not send headers

### ISSUE THREAD

**Issue by BnTejaede** [kaazing/http2-cache.js#24]
The following request fails when sent with http2-cache.js and it is NOT configured to be proxied.

POST:  https://testemops.pdc.org/hp_srv/services/hazards/2/json/edit_hazard

The fetch from Contour sets Content-Type: "application/x-www-form-urlencoded" and the Network tab shows the actual request has content-type:text/plain;charset=UTF-8

**Comment by hthetiot** [comment]
See #28
