### ISSUE TITLE
Paths are not supported in the proxy configuration

### ISSUE THREAD

**Issue by BnTejaede** [kaazing/http2-cache.js#25]
Steps to reproduce: 
1. Set pdc-accelerator/development/origin-server/public/config.json to:
```
{
    "pushURL": "wss://rest-accelerator.example.com:8081/event-stream",
    "transport": "wss://rest-accelerator.example.com:8081/",
    "debug": true,
    "proxy": [
        "https://testemops.pdc.org/hp_srv/services/hazards/t/"
    ]
}
```

2. Open https://rest-accelerator.example.com:8080/

3. Enter the following into the form:
    URL: https://testemops.pdc.org/jwt/v1/auth/login/ 
    Headers: {"Content-type": "application/json"}
    Body: {"username":"ruser14", "password":"ruser"}

4. Send request

Expected: The request is sent directly to the destination server and is not proxied. 
Actual: The request is proxied.

**Comment by BnTejaede** [comment]
I wrote a workaround for this in my own repo so I can continue testing other things. If necessary, I can flesh that out more fully and push it to the repo for review.

**Comment by hthetiot** [comment]
See WIP #27

**Comment by hthetiot** [comment]
Ready here #27
cc @BnTejaede @dpwspoon
