### ISSUE TITLE
Should properly honor request cache invalidators

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/http2-cache.js#47]
```
Cache-Control: must-revalidate
Cache-Control: no-cache
Cache-Control: no-store
Cache-Control: no-transform
Cache-Control: public
Cache-Control: private
Cache-Control: proxy-revalidate
Cache-Control: max-age=<seconds>
Cache-Control: s-maxage=<seconds>
```

**Comment by dpwspoon** [comment]
Note, http2-cache.js is a client cache so...

s-maxage is the same as max-age (we can take the greater value if both appear, I believe).

proxy-revalidate and private/public also have no effect (I believe, please confirm in spec)

**Comment by hthetiot** [comment]
https://github.com/kaazing/http2-cache.js/commit/790499856a7cffeb2a024dd0121a93277943aedb 
https://github.com/kaazing/http2-cache.js/commit/8426adc7e0a49e58eb9557fc9bb86c4cecd0bb8c
