### ISSUE TITLE
Uncacheable responses do not invalidate existing cache

### ISSUE THREAD

**Issue by BnTejaede** [kaazing/http2-cache.js#53]
Steps:
1. Acquire JWT
2. Poll get_hazards with JWT
3. Cache valid responses as they arrive
4. JWT expires
5. Skip caching as the responses have an uncacheable status code.

Expected: The cache is invalidated. If it's the result of a client request, the uncacheable response is returned to the application layer. If it's a push promise, the next client request goes to the accelerator.
Actual: If a cache exists, the application receives it in perpetuity.

**Comment by hthetiot** [comment]
See #55
