### ISSUE TITLE
stale-while-revalidate cache-directive semantics should be respected

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/http2-cache.js#64]
Stale-while-revalidate is defined [here](https://tools.ietf.org/html/rfc5861).

It allows serving a stale cache response if the cache is in the process of refreshing it's entry.  We interpret this to mean, that it is okay to serve it from cache IF there is an outstanding push promise.

This is not properly implemented today: https://github.com/kaazing/http2-cache.js/blob/3cf0baa0927e2fb1320f3de04d952f60bc839cb9/lib/cache.js#L141.

We should only use the stale-while-revalidate value in the comparison `maxAgeAt > staleButRevalidateAt ? maxAgeAt : staleButRevalidateAt;` IF there is a inflight push promise that matches the requestInfo.

If there is no inflight push promise with request info that matches, then we should ignore the stale-while-revalidate cache extension.

**Comment by hthetiot** [comment]
merged https://github.com/kaazing/http2-cache.js/pull/66
