### ISSUE TITLE
Speed up transfer time of payload between worker and index page via transferable (shared array buffer)

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/http2-cache.js#92]
We should investigate using shared array buffer for transferring data across XHR.  The expectation is that this would significantly speed up message delivery times for large responses.  

Suggested steps, implement and test using large payload (1kb, .5 mb, 5mb, 25 mbs, bigger ?).  The implementation should stream (not require a copy) the payload data across a shared array buffer.  

Note, the current test backend system on this repo is VERY slow on sending large payloads over the WS stream library.  This is caused by 4k chunking on the websocket frames AND MAYBE other things (TCP_NO_DELAY not being set).  If we use the in repo backend for benchmarking then we should increase the WebSocket frame size to 64k.

**Comment by hthetiot** [comment]
https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/

**Comment by hthetiot** [comment]
> Specifically, in all release channels, starting with 57:

> The resolution of performance.now() will be reduced to 20µs.
> The SharedArrayBuffer feature is being disabled by default.

**Comment by hthetiot** [comment]
see #89
